POST http://localhost:8080/events
content-type: application/json

{
  "name": "Test event 2",
  "description": "Another test event",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}
