PUT http://localhost:8080/events/5
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNjk5MjgyODAzLCJ1c2VySWQiOjJ9.0v3T0JovPLtzaDnQ6VwSaR2wyyaWnM-0jY5KjhbLgUs

{
  "name": "Updated test event",
  "description": "A test event",
  "location": "Test location (Updated!)",
  "dateTime": "2025-01-01T15:30:00Z"
}